name: Release Info
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        opened,
        edited,
        reopened,
        synchronize,
        ready_for_review,
      ]

jobs:
  generate-pr-description:
    name: Generate the description on the pull request
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: octue/generate-pull-request-description@1.0.0.beta-2
        id: pr-description
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update pull request body
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ steps.pr-description.outputs.pull_request_description }}
          token: ${{ secrets.GITHUB_TOKEN }}

  check-pr:
    if: ${{ github.actor != 'dependabo[bot]' }}
    needs: generate-pr-description
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - id: setup-secrets
        name: Setup secrets
        uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: "secret"
          secret_fields: "password"
          mask_secrets: "password"

      - uses: actions/checkout@v4

      - uses: jefflinse/pr-semver-bump@v1.7.3
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ steps.setup-secrets.outputs.secret1 }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          noop-labels: |
            documentation change
            dependencies
            skip-release
          require-release-notes: true
          release-notes-prefix: "<!--- START AUTOGENERATED NOTES --->"
          release-notes-suffix: "<!--- END AUTOGENERATED NOTES --->"
          with-v: false
          base-branch: false
